[[redirects]]
  from = "/pity"
  to = "/"
  status = 200

[[redirects]]
  from = "/recruit"
  to = "/"
  status = 200
  
 [[redirects]]
  from = "/recHis"
  to = "/"
  status = 200
  
 [[redirects]]
  from = "/stats"
  to = "/"
  status = 200
